### ISSUE TITLE
Local server error: GeoJSON file not found for '_template'.

### ISSUE THREAD

**Issue by aido179** [codeforgermany/click_that_hood#268]
Forked, cloned, `npm install`ed and `npm start`ed.

Error output:
    Initializing…
    GeoJSON file not found for '_TEMPLATE'. Aborting server start.

```
npm ERR! click_that_hood@0.0.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the click_that_hood@0.0.1 start script.
```

**Comment by mwichary** [comment]
Weird! That works for me. The underscore should be caught in app.js@103. If
you move _TEMPLATE and _work-in-progress to their parent directory that
should help, although I wonder what else will go wrong if this fails
randomly…

What’s the path you’re running this from? What’s the OS/environment?

**Comment by aido179** [comment]
In the project path. Windows 8. It could possibly be \ vs /. 

I managed to get it running further by editing app.js@103:
    if (metadataFilePath.indexOf('/_') == -1 && metadataFilePath.indexOf('TEMPLATE') == -1) {
Though it then fell over with denmark, so obviously the test for '/_' is failing on windows as it is entering the `_work-in-progress` directory. I then deleted the `_work-in-progress` directory and it worked no problem.

**Comment by specious** [comment]
This was probably fixed right here: https://github.com/codeforgermany/click_that_hood/commit/3e90b35e2c88bb076f8e31b454c117dc3a646563

If this issue resurfaces, please reopen.
