### ISSUE TITLE
Problem with the Travis CI build script?

### ISSUE THREAD

**Issue by DainialPadraig** [codeforgermany/click_that_hood#286]
Submitted pull request #285 Add Tucson Neighborhoods and the Travis CI build failed. Error messages showed outdated Node version and that jshint failed to run. I can't see anything wrong with the GeoJSON and JSON files in the pull request, so I'm guessing there's an issue with the Travis CI setup.
If there are issues with the JSON, I would be happy to fix them, but they worked great on the fork I tested with - and I did make sure the fork was up to date with the master before testing and submitting the pull request.

**Comment by mwichary** [comment]
The build script doesn’t work and I don’t think it ever did. If it works locally, it’s probably good. I’ll try to take a look soon…

**Comment by DainialPadraig** [comment]
Well, that's good to know. I was worried there was something wrong with the pull request I submitted!
