### ISSUE TITLE
Czechoslovakia in 1938

### ISSUE THREAD

**Issue by musland** [codeforgermany/click_that_hood#287]
In the Europe 1938 map, the Czech part (what is now the Czech Republic) of Czechoslovakia is falsely claimed to be part of Poland. The Czechoslovakia that is supposed to be correct is in fact only Slovakia.

**Comment by mwichary** [comment]
Please send a patch! :·)

**Comment by jmacura** [comment]
This is terribly incorrect!

![image](https://user-images.githubusercontent.com/5598693/144724154-cadd7add-bddb-44a2-9e36-c7314674cc16.png)
![image](https://user-images.githubusercontent.com/5598693/144724159-aa7dd365-c1a9-4c82-8e83-934d6a58ad81.png)
