### ISSUE TITLE
brazil_states.geojson

### ISSUE THREAD

**Issue by whiterr** [codeforgermany/click_that_hood#305]
Hi,'brazil_states.geojson' can not use,showing blank in jupyter notebook.

**Comment by specious** [comment]
There appears to be nothing wrong with the [data file](https://github.com/codeforgermany/click_that_hood/blob/762f3ded02727c2c0e3ca1efd1736bc496fda673/public/data/brazil-states.geojson) and it functions perfectly in the app.

If you can provide more information on the issue, feel free to reopen this.
