### ISSUE TITLE
Rename default "master" branch to "main"

### ISSUE THREAD

**Issue by fnogatz** [codeforgermany/click_that_hood#315]
Note: This should be done only after all [pull requests](https://github.com/codeforgermany/click_that_hood/pulls) have been reviewed.

**Comment by specious** [comment]
`master` is the default in git.

**Comment by fnogatz** [comment]
No, not anymore. A brief summary of the recent developments regarding the shift towards `main` instead is given in these articles of [GitLab](https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/) and [GitHub](https://github.com/github/renaming).

**Comment by fnogatz** [comment]
Today, I renamed the repository's default branch from `master` to `main`.
