### ISSUE TITLE
Automated builds need to be reinstated (manual intervention needed)

### ISSUE THREAD

**Issue by specious** [codeforgermany/click_that_hood#316]
The automated builds on [travis-ci.org](https://travis-ci.org/) have [ceased](https://blog.travis-ci.com/2021-05-07-orgshutdown) due to it being retired.

It looks like the builds can be migrated to [travis-ci.com](https://travis-ci.com/).

**Comment by fnogatz** [comment]
Currently, the CI is only used for running the jshint tests. In the long term, we might also use it for deployment. However, I would suggest to rely on [*GitHub Actions*](https://github.com/features/actions) instead of Travis.

**Comment by specious** [comment]
I second that.
