### ISSUE TITLE
Facebook share button is broken

### ISSUE THREAD

**Issue by epaulson** [codeforgermany/click_that_hood#324]
The 'Share to Facebook' button is broken - does Code for Germany have access to the Facebook app admin settings?

<img width="889" alt="Screen Shot 2021-11-22 at 1 19 52 PM" src="https://user-images.githubusercontent.com/315267/142922330-33dbb911-9321-42d3-a8a8-f0edcc5df06c.png">

**Comment by fnogatz** [comment]
Actually, I would suggest removing the *Share via Facebook/Twitter/...* functionality at all. Code for Germany has no access to the Facebook app settings.

**Comment by epaulson** [comment]
I think you can make a pretty convincing case that the social shares were super-effective for spreading awareness of the game - see the 'You Don't Know Africa' experience, which is using the CTH codebase: http://www.davidbauer.ch/2013/12/01/youdontknowafrica-learnings-from-an-accidental-worldwide-internet-hit/

but I dunno if Facebook shares of game results would still as "viral" today as they were 10 years ago. 

Facebook sharing has changed a lot since 2013 and maybe we're better off using the newer, simpler sharing setup that doesn't need a facebook "app id" and doesn't load any javascript from FB. That means we can't post things like "I solved the game in 1 minute and 19 seconds" but instead the button would just share the site, just like if someone copy/pasted the link into Facebook themselves.

If we really do want to restore the personalized "I solved the game in 1:23 time" message, we can register for a new app. 

Personally, I'm fine if we don't have the personalized "I solved the game in 1:23 time" message, but I do think we should keep some kind of social share button, especially for Facebook, so we should at a minimum change the current FB share button to be the generic Facebook sharer.php link

**Comment by fnogatz** [comment]
Fixed via #333.
